In [1]:
from pathlib import Path
print(Path.cwd())

/Users/yogithagujjarlapudi/AI-ML Course/AI-ML-PROJECTS/AI-ML/Customer-Support-Ticket-Intelligence/notebooks

In [3]:
import pandas as pd

print(f"Pandas version: {pd.__version__}")

Pandas version: 3.0.5

In [4]:
DATA_PATH = Path("../data/raw/customer_support_tickets.csv")

print(DATA_PATH)
print(f"Dataset exists: {DATA_PATH.exists()}")

../data/raw/customer_support_tickets.csv
Dataset exists: True

In [5]:
#Loading data to dataframe

df = pd.read_csv(DATA_PATH)
print("Data loaded successfully")

Data loaded successfully

In [6]:
df.shape

(28587, 16)

In [7]:
df.columns.tolist()

['subject',
 'body',
 'answer',
 'type',
 'queue',
 'priority',
 'language',
 'version',
 'tag_1',
 'tag_2',
 'tag_3',
 'tag_4',
 'tag_5',
 'tag_6',
 'tag_7',
 'tag_8']

In [8]:
df.head()

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Vielen Dank für die Meldung des kritischen Sic...,Incident,Technical Support,high,de,51,Security,Outage,Disruption,Data Breach,NaN,NaN,NaN,NaN
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Thank you for your inquiry. Our products suppo...,Request,Returns and Exchanges,medium,en,51,Product,Feature,Tech Support,NaN,NaN,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Thank you for your inquiry. Our product suppor...,Problem,Sales and Pre-Sales,medium,en,51,Product,Feature,Feedback,Tech Support,NaN,NaN,NaN,NaN

In [9]:
df[["subject", "body", "queue", "language"]].head()

,subject,body,queue,language
0,Wesentlicher Sicherheitsvorfall,"Sehr geehrtes Support-Team,\n\nich möchte eine...",Technical Support,de
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...",Technical Support,en
2,Query About Smart Home System Integration Feat...,"Dear Customer Support Team,\n\nI hope this mes...",Returns and Exchanges,en
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",Billing and Payments,en
4,Question About Marketing Agency Software Compa...,"Dear Support Team,\n\nI hope this message reac...",Sales and Pre-Sales,en

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  str
 1   body      28587 non-null  str
 2   answer    28580 non-null  str
 3   type      28587 non-null  str
 4   queue     28587 non-null  str
 5   priority  28587 non-null  str
 6   language  28587 non-null  str
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  str
 9   tag_2     28574 non-null  str
 10  tag_3     28451 non-null  str
 11  tag_4     25529 non-null  str
 12  tag_5     14545 non-null  str
 13  tag_6     5874 non-null   str
 14  tag_7     2040 non-null   str
 15  tag_8     565 non-null    str
dtypes: int64(1), str(15)
memory usage: 3.5 MB

In [11]:
df["language"].value_counts(dropna=False)

language
en    16338
de    12249
Name: count, dtype: int64

In [12]:
df["language"].value_counts(normalize=True, dropna=False).mul(100).round(2)

language
en    57.15
de    42.85
Name: proportion, dtype: float64

In [13]:
df["queue"].value_counts(dropna=False)

queue
Technical Support                  8362
Product Support                    5252
Customer Service                   4268
IT Support                         3433
Billing and Payments               2788
Returns and Exchanges              1437
Service Outages and Maintenance    1148
Sales and Pre-Sales                 918
Human Resources                     576
General Inquiry                     405
Name: count, dtype: int64

In [14]:
df["queue"].nunique()

10

In [15]:
SELECTED_QUEUES = [
    "Billing and Payments",
    "Customer Service",
    "Product Support",
    "Technical Support",
]

df[df["queue"].isin(SELECTED_QUEUES)]["queue"].value_counts()

queue
Technical Support       8362
Product Support         5252
Customer Service        4268
Billing and Payments    2788
Name: count, dtype: int64

In [23]:
#Creating EN only DataFrame

english_df = df[df["language"] == "en"].copy()
english_df.shape

(16338, 16)

In [24]:
#Selection proeject required queues

project_df = english_df[english_df["queue"].isin(SELECTED_QUEUES)].copy()
project_df.shape

(11815, 16)

In [25]:
project_df["queue"].value_counts()

queue
Technical Support       4737
Product Support         3073
Customer Service        2410
Billing and Payments    1595
Name: count, dtype: int64

In [26]:
project_df["queue"].value_counts(normalize=True).mul(100).round(2)

queue
Technical Support       40.09
Product Support         26.01
Customer Service        20.40
Billing and Payments    13.50
Name: proportion, dtype: float64

In [29]:
#Display 2 tickets randomly

project_df.groupby("queue").sample(n=2, random_state=42)[["subject","body","queue"]]

,subject,body,queue
16649,Request for Details on Adobe Sign HelloSign Su...,Can you please provide comprehensive details o...,Billing and Payments
19958,Inquiry Regarding the Billing Structure of Pro...,Could you please provide details about the bil...,Billing and Payments
14825,Required Support for Digital Marketing Strategies,The agency is facing a decline in client engag...,Customer Service
13743,Required Assistance in Digital Marketing,Is there a possibility to share marketing stra...,Customer Service
20283,Irregular Data Analytics Outputs on Investment...,The investment optimization tool is showing ir...,Product Support
28129,Reported Drop in Online Engagement,"Customer Support, we are compiling a report on...",Product Support
530,Inquiry for In-Depth Platform Architecture Det...,"Dear Customer Support Team,\n\nI hope this mes...",Technical Support
20442,Inquiry About Integrating IBM SPSS Statistics ...,Seeking information on integrating IBM SPSS St...,Technical Support

In [31]:
project_df.head()

,subject,body,answer,type,queue,priority,language,version,tag_1,tag_2,tag_3,tag_4,tag_5,tag_6,tag_7,tag_8
1,Account Disruption,"Dear Customer Support Team,\n\nI am writing to...","Thank you for reaching out, <name>. We are awa...",Incident,Technical Support,high,en,51,Account,Disruption,Outage,IT,Tech Support,NaN,NaN,NaN
3,Inquiry Regarding Invoice Details,"Dear Customer Support Team,\n\nI hope this mes...",We appreciate you reaching out with your billi...,Request,Billing and Payments,low,en,51,Billing,Payment,Account,Documentation,Feedback,NaN,NaN,NaN
5,Feature Query,"Dear Customer Support,\n\nI hope this message ...",Thank you for your inquiry. Please specify whi...,Request,Technical Support,high,en,51,Feature,Product,Documentation,Feedback,NaN,NaN,NaN,NaN
7,Connectivity Problems with Printer on MacBook Pro,"Dear Support Team,\n\nI am reporting a recurri...",Thank you for reaching out regarding the conne...,Incident,Technical Support,medium,en,51,Network,Hardware,Performance,Bug,Compatibility,NaN,NaN,NaN
10,VPN Access Issue,"Customer Support,\n\nWe are encountering a dis...",Thank you for reporting this problem. Please p...,Incident,Product Support,medium,en,51,Network,Disruption,VPN,Tech Support,NaN,NaN,NaN,NaN

In [32]:
print("Original dataset:", df.shape)
print("English dataset:", english_df.shape)
print("Project dataset:", project_df.shape)

Original dataset: (28587, 16)
English dataset: (16338, 16)
Project dataset: (11815, 16)

In [33]:
project_df["queue"].value_counts()

queue
Technical Support       4737
Product Support         3073
Customer Service        2410
Billing and Payments    1595
Name: count, dtype: int64

In [34]:
project_df["queue"].value_counts(normalize=True).mul(100).round(2)

queue
Technical Support       40.09
Product Support         26.01
Customer Service        20.40
Billing and Payments    13.50
Name: proportion, dtype: float64

In [35]:
project_df[["subject", "body", "queue"]].isna().sum()

subject    1842
body          0
queue         0
dtype: int64

In [38]:
#Filling missing values of subject with emply string

project_df["subject"].fillna("")

1                                       Account Disruption
3                        Inquiry Regarding Invoice Details
5                                            Feature Query
7        Connectivity Problems with Printer on MacBook Pro
10                                        VPN Access Issue
                               ...
28573    Concerns About Investment Data Integration Pro...
28578                      Problem with Billing Adjustment
28580    Urgent: Incident Involving Data Breach in Medi...
28582         Performance Problem with Data Analytics Tool
28586            Inquiry About Project Management Features
Name: subject, Length: 11815, dtype: str